GET http://localhost:5170/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InNoYWpqYWQiLCJzdWIiOiJzaGFqamFkIiwianRpIjoiMmJlYmVhYWQiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MTcwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA3MCJdLCJuYmYiOjE3NjUyNzQyNDQsImV4cCI6MTc3MzA1MDI0NCwiaWF0IjoxNzY1Mjc0MjQ0LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.5WV4k1fvPdecT0KAKlLTuEBaMACOuOinGX3D4M_il5E


###
GET http://localhost:5170/mygames 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiZDMyNGQ0Y2MiLCJyb2xlIjoicGxheWVyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTE3MCIsImh0dHBzOi8vbG9jYWxob3N0OjcwNzAiXSwibmJmIjoxNzY1Mjc3Nzg2LCJleHAiOjE3NzMwNTM3ODYsImlhdCI6MTc2NTI3Nzc4NywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.UiRjDuV7yjTUDw1woyCjg71DgAQtUt0ls0KgGGTzLbo